In [96]:
%pip install pandas
%pip install openpyxl
%pip install scikit-learn

Requirement already satisfied: pandas in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fne\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\fne\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)

Requirement already satisfied: openpyxl in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)

Collecting scikit-learn
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\fne\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (2.2.6)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   - -------------------------------------- 1.3/41.3 MB 7.4 MB/s eta 0:00:06
   --- ------------------------------------ 3.4/41.3 MB 8.7 MB/s eta 0:00:05
   ----- ---------------------------------- 5.5/41.3 MB 9.1 MB/s eta 0:00:04
   ------ --------------------------------- 6.8/41.3 MB 8.7 MB/s eta 0:00:04
   -------- ------------------------------- 8.9/41.3 MB 8.8 MB/s eta 0:00:04
   ---------- ----------------------------- 10.7/41.3 MB 8.7 MB/s eta 0:00:04
   ----------- ---------------------------- 12.3/41.3 MB 8.6 MB/s eta 0:00:04
   ------------ --------------------------- 13.4/41.3 MB 8.1 MB/s eta 0:00:04
   -------------- ------------------------- 14.9/41.3 MB 8.0 MB/s eta 0:00:04
   --------------- ------------------------ 16.0/41.3 MB 7.9 MB/s eta 0:00:04
   ----------------- ---------------------- 17.6/41.3 MB 7.6 MB/s eta 0:00:04
   ------------------ --------------------- 19.1/41.3 MB 7.6 MB/s eta 0:00:03
   -------------------- ------------------- 20.7/41.3 MB 7.6 MB/s eta 0:00:03
   --------------------- ------------------ 22.3/41.3 MB 7.6 MB/s eta 0:00:03
   ---------------------- ----------------- 23.3/41.3 MB 7.5 MB/s eta 0:00:03
   ------------------------ --------------- 25.2/41.3 MB 7.5 MB/s eta 0:00:03
   ------------------------- -------------- 26.7/41.3 MB 7.5 MB/s eta 0:00:02
   --------------------------- ------------ 28.0/41.3 MB 7.5 MB/s eta 0:00:02
   ---------------------------- ----------- 29.4/41.3 MB 7.4 MB/s eta 0:00:02
   ----------------------------- ---------- 30.9/41.3 MB 7.4 MB/s eta 0:00:02
   ------------------------------- -------- 32.0/41.3 MB 7.3 MB/s eta 0:00:02
   ------------------------------- -------- 32.5/41.3 MB 7.2 MB/s eta 0:00:02
   -------------------------------- ------- 33.6/41.3 MB 7.1 MB/s eta 0:00:02
   -------------------------------- ------- 33.8/41.3 MB 6.9 MB/s eta 0:00:02
   --------------------------------- ------ 34.6/41.3 MB 6.7 MB/s eta 0:00:01
   --------------------------------- ------ 34.9/41.3 MB 6.6 MB/s eta 0:00:01
   ---------------------------------- ----- 35.1/41.3 MB 6.2 MB/s eta 0:00:01
   ---------------------------------- ----- 35.1/41.3 MB 6.2 MB/s eta 0:00:01
   ---------------------------------- ----- 35.4/41.3 MB 5.8 MB/s eta 0:00:02
   ---------------------------------- ----- 35.7/41.3 MB 5.7 MB/s eta 0:00:01
   ---------------------------------- ----- 35.9/41.3 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 35.9/41.3 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 35.9/41.3 MB 5.6 MB/s eta 0:00:01
   ----------------------------------- ---- 36.2/41.3 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 36.4/41.3 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 36.4/41.3 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 37.0/41.3 MB 4.8 MB/s eta 0:00:01
   ------------------------------------ --- 37.2/41.3 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 37.7/41.3 MB 4.6 MB/s eta 0:00:01
   ------------------------------------ --- 38.0/41.3 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 38.5/41.3 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 38.8/41.3 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 39.3/41.3 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 40.1/41.3 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 4.2 MB/s  0:00:09
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.7.2 scipy-1.15.3 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\fne\appdata\local\programs\python\python310\lib\site-packages)

In [2]:
import pandas as pd
import numpy as np
import os
import openpyxl
import csv

In [3]:


excel = openpyxl.load_workbook("./raw/fatal_overdose.xlsx")
sheet = excel['Data']

with open("./raw/fatal_overdose.csv", 'w', newline="") as f:
    writer = csv.writer(f)

    for row in sheet.rows:
        writer.writerow([cell.value for cell in row])

df = pd.DataFrame(pd.read_csv("./raw/fatal_overdose.csv"))

print(df)

      Jurisdiction  year  alldrug_deaths  alldrug_rate  opioids_deaths  \
0           Alaska  2020             171          23.8             111
1          Arizona  2020            2412          34.0            1867
2         Colorado  2020            1329          22.4             976
3      Connecticut  2020            1374          39.4            1278
4         Delaware  2020             446          47.4             417
..             ...   ...             ...           ...             ...
187       Virginia  2024            1559          17.9            1181
188     Washington  2024            2988          37.0            2470
189  West Virginia  2024             782          46.3             611
190      Wisconsin  2024            1054          18.1             783
191        Wyoming  2024              95          16.6              52

     opioids_rate  imfs_deaths  imfs_rate  heroin_deaths  heroin_rate  ...  \
0            15.4           58        8.0             48          6.7  ...
1            26.3         1474       20.8            288          4.1  ...
2            16.3          558        9.3            280          4.6  ...
3            36.7         1158       33.4            267          7.5  ...
4            44.5          372       40.0            109         11.7  ...
..            ...          ...        ...            ...          ...  ...
187          13.6         1082       12.5            136          1.5  ...
188          30.6         2311       28.7             62          0.7  ...
189          36.8          541       32.7             19       9999.0  ...
190          13.6          689       12.1            194          3.4  ...
191           9.2           25        4.7              1       9999.0  ...

     rx_drugs_deaths  rx_drugs_percent  illegal_drugs_deaths  \
0                 57              33.3                    60
1                773              32.2                   940
2                336              26.8                   469
3                227              16.5                   728
4                156              35.2                   247
..               ...               ...                   ...
187              498              31.9                   696
188              740              25.2                  1334
189               63               8.3                   196
190              404              40.1                   424
191               14              16.3                    12

     illegal_drugs_percent  counterfeit_pills_deaths  \
0                     35.1                        12
1                     39.1                       422
2                     37.5                       116
3                     53.0                        39
4                     55.8                        16
..                     ...                       ...
187                   44.6                        98
188                   45.5                       234
189                   25.7                        13
190                   42.1                        42
191                   14.0                         3

     counterfeit_pills_percent  ever_SUDtrt_deaths  ever_SUDtrt_percent  \
0                          7.0                  11                  6.4
1                         17.6                 270                 11.2
2                          9.3                 141                 11.3
3                          2.8                 207                 15.1
4                          3.6                  99                 22.3
..                         ...                 ...                  ...
187                        6.3                 253                 16.2
188                        8.0                 329                 11.2
189                        1.7                  93                 12.2
190                        4.2                 135                 13.4
191                        3.5                   4                  4.7

     rx_OUD_deaths  rx_OUD_percent
0                7             4.1
1               58             2.4
2               43             3.4
3               56             4.1
4               33             7.4
..             ...             ...
187            170            10.9
188            187             6.4
189             67             8.8
190             75             7.4
191              2             2.3

[192 rows x 274 columns]

In [5]:
numeric_df = df.select_dtypes(include=np.number).copy()
categorical_df = df.select_dtypes(exclude=np.number).copy()

In [ ]:
mask = categorical_df.isin(['<0.1']).any(axis=1)

# Keep only the rows where the mask is False
df_clean = categorical_df[~mask]
df_clean

In [62]:
df_clean.dtypes

Jurisdiction                       object
combo1_drugs                       object
combo2_drugs                       object
combo3_drugs                       object
combo4_drugs                       object
combo5_drugs                       object
carfentanil_percent                object
parafluorofentanyl_percent         object
other_illegal_opioids_percent      object
nitazenes_percent                  object
isotonitazene_percent              object
metonitazene_percent               object
adulterants_sedatives_percent      object
xylazine_percent                   object
gabapentin_percent                 object
illegal_benzodiazepines_percent    object
bromazolam_percent                 object
etizolam_percent                   object
flualprazolam_percent              object
ketamine_percent                   object
kratom_percent                     object
synthetic_cannabinoid_percent      object
cathinones_percent                 object
aian_nh_percent                    object
asian_nh_percent                   object
nhpi_nh_percent                    object
age_under15_percent                object
male_under15_percent               object
otherroute_percent                 object
dtype: object

In [111]:
'''

##################################

'''
perc_obj_rows = df_clean.drop(df_clean[['Jurisdiction','combo1_drugs','combo2_drugs','combo3_drugs','combo4_drugs','combo5_drugs']], axis=1)
perc_df = perc_obj_rows.astype(float)

# Replace 9999.0 with NaN, then fill with the mean of each column
perc_df = perc_df.replace(9999.0, np.nan).fillna(perc_df[perc_df != 9999.0].mean())


obj_rows = df_clean.drop(perc_df, axis=1)
obj_rows.nunique()

Jurisdiction    40
combo1_drugs     5
combo2_drugs     7
combo3_drugs     9
combo4_drugs    16
combo5_drugs    20
dtype: int64

In [120]:
import pandas as pd
import numpy as np

obj_rows['target'] = None
# 1. Calculate the mean target value for each drug
# We melt the dataframe to see every instance of a drug regardless of column
melted = obj_rows.melt(id_vars=['target'], value_vars=['combo1_drugs', 'combo2_drugs', 'combo3_drugs', 'combo4_drugs', 'combo5_drugs'])
drug_means = melted.groupby('value')['target'].mean().to_dict()

# 2. Define your weights (Column 1 is most important)
# You can use linear decay, exponential decay, or custom weights
weights = {
    'combo1_drugs': 1.0,
    'combo2_drugs': 0.8,
    'combo3_drugs': 0.6,
    'combo4_drugs': 0.4,
    'combo5_drugs': 0.2
}

# 3. Apply the encoding and the weights
encoded_df = obj_rows.copy()

for col, weight in weights.items():
    # Replace string with its mean target value, then multiply by the importance weight
    encoded_df[f'{col}_weighted'] = encoded_df[col].map(drug_means) * weight

# 4. Create a final aggregate feature
weighted_cols = [f'{col}_weighted' for col in weights.keys()]
encoded_df['total_combo_score'] = encoded_df[weighted_cols].sum(axis=1)

In [121]:
encoded_df

,Jurisdiction,combo1_drugs,combo2_drugs,combo3_drugs,combo4_drugs,combo5_drugs,target,combo1_drugs_weighted,combo2_drugs_weighted,combo3_drugs_weighted,combo4_drugs_weighted,combo5_drugs_weighted,total_combo_score
0,Alaska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE",HEROIN AND METHAMPHETAMINE,None,NaN,NaN,NaN,NaN,NaN,0.0
2,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE",None,NaN,NaN,NaN,NaN,NaN,0.0
3,Connecticut,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0
4,Delaware,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
5,District of Columbia,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0
6,Georgia,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",None,NaN,NaN,NaN,NaN,NaN,0.0
7,Iowa,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
8,Kansas,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
10,Maine,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
14,Minnesota,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",None,NaN,NaN,NaN,NaN,NaN,0.0
15,Mississippi,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",None,NaN,NaN,NaN,NaN,NaN,0.0
16,Montana,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,"HEROIN, NO OTHER OPIOIDS OR STIMULANTS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",None,NaN,NaN,NaN,NaN,NaN,0.0
17,Nebraska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,None,NaN,NaN,NaN,NaN,NaN,0.0
18,Nevada,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
19,New Hampshire,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
21,New Mexico,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE","HEROIN AND PRESCRIPTION OPIOIDS, NO STIMULANTS",None,NaN,NaN,NaN,NaN,NaN,0.0
24,Oklahoma,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",HEROIN AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
25,Oregon,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",HEROIN AND METHAMPHETAMINE,"HEROIN, NO OTHER OPIOIDS OR STIMULANTS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
28,Rhode Island,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
29,South Dakota,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
30,Tennessee,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
31,Utah,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",HEROIN AND METHAMPHETAMINE,"HEROIN, NO OTHER OPIOIDS OR STIMULANTS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",None,NaN,NaN,NaN,NaN,NaN,0.0
32,Vermont,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
34,West Virginia,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
35,Alaska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
37,Arkansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
38,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
39,Connecticut,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
40,Delaware,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0
41,District of Columbia,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0
43,Hawaii,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","HEROIN, NO OTHER OPIOIDS OR STIMULANTS",None,NaN,NaN,NaN,NaN,NaN,0.0
44,Iowa,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",None,NaN,NaN,NaN,NaN,NaN,0.0
45,Kansas,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
47,Maine,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
49,Massachusetts,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS...",None,NaN,NaN,NaN,NaN,NaN,0.0
51,Minnesota,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
52,Nebraska,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
53,Nevada,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,HEROIN AND METHAMPHETAMINE,None,NaN,NaN,NaN,NaN,NaN,0.0
54,New Hampshire,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
56,New Mexico,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, PRESCRIPTION...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
59,Oklahoma,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
60,Oregon,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,HEROIN AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",None,NaN,NaN,NaN,NaN,NaN,0.0
61,Overall,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
63,Rhode Island,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
64,South Dakota,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
65,Utah,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","HEROIN, NO OTHER OPIOIDS OR STIMULANTS",None,NaN,NaN,NaN,NaN,NaN,0.0
66,Vermont,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0
68,West Virginia,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS...",None,NaN,NaN,NaN,NaN,NaN,0.0
69,Alaska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
71,Arkansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
72,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
73,Connecticut,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
74,Delaware,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
75,District of Columbia,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0
77,Hawaii,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
79,Iowa,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
80,Kansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
82,Maine,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
85,Minnesota,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
86,Mississippi,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
87,Missouri,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
88,Montana,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
89,Nebraska,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
90,New Hampshire,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",None,NaN,NaN,NaN,NaN,NaN,0.0
92,New Mexico,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
95,Oklahoma,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
96,Oregon,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",ILLEGALLY-MADE FENTANYLS AND COCAINE,None,NaN,NaN,NaN,NaN,NaN,0.0
99,Rhode Island,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",None,NaN,NaN,NaN,NaN,NaN,0.0
100,Tennessee,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,None,NaN,NaN,NaN,NaN,NaN,0.0
101,Utah,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,None,NaN,NaN,NaN,NaN,NaN,0.0
102,Vermont,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE",None,NaN,NaN,NaN,NaN,NaN,0.0

In [118]:
obj_rows

,Jurisdiction,combo1_drugs,combo2_drugs,combo3_drugs,combo4_drugs,combo5_drugs
0,Alaska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE",HEROIN AND METHAMPHETAMINE
2,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE"
3,Connecticut,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
4,Delaware,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
5,District of Columbia,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
6,Georgia,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL..."
7,Iowa,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
8,Kansas,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
10,Maine,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
14,Minnesota,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL..."
15,Mississippi,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL..."
16,Montana,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,"HEROIN, NO OTHER OPIOIDS OR STIMULANTS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ..."
17,Nebraska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE
18,Nevada,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
19,New Hampshire,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
21,New Mexico,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE","HEROIN AND PRESCRIPTION OPIOIDS, NO STIMULANTS"
24,Oklahoma,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",HEROIN AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
25,Oregon,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",HEROIN AND METHAMPHETAMINE,"HEROIN, NO OTHER OPIOIDS OR STIMULANTS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
28,Rhode Island,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
29,South Dakota,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
30,Tennessee,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
31,Utah,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",HEROIN AND METHAMPHETAMINE,"HEROIN, NO OTHER OPIOIDS OR STIMULANTS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ..."
32,Vermont,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
34,West Virginia,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
35,Alaska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
37,Arkansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
38,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
39,Connecticut,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
40,Delaware,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
41,District of Columbia,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
43,Hawaii,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","HEROIN, NO OTHER OPIOIDS OR STIMULANTS"
44,Iowa,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL..."
45,Kansas,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
47,Maine,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
49,Massachusetts,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS..."
51,Minnesota,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
52,Nebraska,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
53,Nevada,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,HEROIN AND METHAMPHETAMINE
54,New Hampshire,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS"
56,New Mexico,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, PRESCRIPTION...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
59,Oklahoma,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
60,Oregon,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,HEROIN AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH..."
61,Overall,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
63,Rhode Island,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
64,South Dakota,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
65,Utah,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","HEROIN, NO OTHER OPIOIDS OR STIMULANTS"
66,Vermont,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
68,West Virginia,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS..."
69,Alaska,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",ILLEGALLY-MADE FENTANYLS AND COCAINE
71,Arkansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
72,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
73,Connecticut,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
74,Delaware,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
75,District of Columbia,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
77,Hawaii,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
79,Iowa,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
80,Kansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
82,Maine,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
85,Minnesota,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
86,Mississippi,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
87,Missouri,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
88,Montana,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
89,Nebraska,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
90,New Hampshire,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS"
92,New Mexico,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE
95,Oklahoma,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
96,Oregon,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH...",ILLEGALLY-MADE FENTANYLS AND COCAINE
99,Rhode Island,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
100,Tennessee,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,ILLEGALLY-MADE FENTANYLS AND COCAINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...
101,Utah,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS","PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",HEROIN AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE
102,Vermont,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMUL...","ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE"
103,Virginia,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND COCAINE,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS"
104,West Virginia,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS..."
105,Alabama,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS"
106,Alaska,ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPH..."
108,Arkansas,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM...",ILLEGALLY-MADE FENTANYLS AND COCAINE
109,Colorado,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE,"METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS",ILLEGALLY-MADE FENTANYLS AND COCAINE,"PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIM..."
110,Connecticut,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...",ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIO...,"COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS..."
111,Delaware,ILLEGALLY-MADE FENTANYLS AND COCAINE,"ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR ...","COCAINE, NO OTHER STIMULANTS OR OPIOIDS","ILLEGALLY-MADE FENTANYLS, COCAINE, AND METHAMP...",ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE

In [94]:
obj_rows.combo3_drugs.unique()

array(['PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIOIDS, NO STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE',
       'HEROIN AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS AND COCAINE',
       'ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR STIMULANTS',
       'COCAINE, NO OTHER STIMULANTS OR OPIOIDS',
       'METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS'], dtype=object)

In [97]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 1. Get all unique values across the entire slice of the dataframe
all_values = pd.concat([df['combo1_drugs'], df['combo2_drugs'], df['combo3_drugs'], df['combo4_drugs'], df['combo5_drugs']]).unique()

# 2. Fit one encoder for everything
le = LabelEncoder()
le.fit(all_values)

# 3. Transform all columns using the same encoder
for col in ['combo1_drugs','combo2_drugs','combo3_drugs','combo4_drugs','combo5_drugs']:
    df[col] = le.transform(df[col])

In [98]:
all_values

array(['METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS',
       'ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND COCAINE',
       'PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPHETAMINE',
       'COCAINE, NO OTHER STIMULANTS OR OPIOIDS',
       'ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIOIDS, NO STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMULANTS',
       'HEROIN AND METHAMPHETAMINE',
       'HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE',
       'HEROIN, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS, HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, COCAINE, AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS, AND COCAINE',
       'HEROIN AND PRESCRIPTION OPIOIDS, NO STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE',
       'NON-SPECIFIC OPIOIDS, NO OTHER OPIOIDS OR STIMULANTS',
       'PRESCRIPTION OPIOIDS AND METHAMPHETAMINE',
       'COCAINE AND METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS'],
      dtype=object)

In [93]:
obj_rows.combo5_drugs.unique()

array(['HEROIN AND METHAMPHETAMINE',
       'HEROIN, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, HEROIN, AND COCAINE',
       'PRESCRIPTION OPIOIDS, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND HEROIN, NO STIMULANTS',
       'COCAINE, NO OTHER STIMULANTS OR OPIOIDS',
       'ILLEGALLY-MADE FENTANYLS AND PRESCRIPTION OPIOIDS, NO STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND METHAMPHETAMINE',
       'HEROIN AND PRESCRIPTION OPIOIDS, NO STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS AND COCAINE',
       'HEROIN, NO OTHER OPIOIDS OR STIMULANTS',
       'ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS, AND COCAINE',
       'METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS',
       'ILLEGALLY-MADE FENTANYLS, HEROIN, AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, PRESCRIPTION OPIOIDS, AND METHAMPHETAMINE',
       'ILLEGALLY-MADE FENTANYLS, COCAINE, AND METHAMPHETAMINE',
       'NON-SPECIFIC OPIOIDS, NO OTHER OPIOIDS OR STIMULANTS',
       'PRESCRIPTION OPIOIDS AND METHAMPHETAMINE',
       'COCAINE AND METHAMPHETAMINE, NO OTHER STIMULANTS OR OPIOIDS'],
      dtype=object)

In [45]:
pd.set_option('display.max_rows', None)
df_clean.dtypes

Jurisdiction                        object
year                                 int64
alldrug_deaths                       int64
alldrug_rate                       float64
opioids_deaths                       int64
opioids_rate                       float64
imfs_deaths                          int64
imfs_rate                          float64
heroin_deaths                        int64
heroin_rate                        float64
rxopioids_deaths                     int64
rxopioids_rate                     float64
stimulant_deaths                     int64
stimulant_rate                     float64
cocaine_deaths                       int64
cocaine_rate                       float64
meth_deaths                          int64
meth_rate                          float64
nonopioid_sedatives_deaths           int64
nonopioid_sedatives_rate           float64
benzodiazepines_deaths               int64
benzodiazepines_rate               float64
opioids_percent                    float64
imfs_percent                       float64
heroin_percent                     float64
rxopioids_percent                  float64
stimulant_percent                  float64
cocaine_percent                    float64
meth_percent                       float64
nonopioid_sedatives_percent        float64
benzodiazepines_percent            float64
combo1_drugs                        object
combo1_deaths                        int64
combo1_percent                     float64
combo2_drugs                        object
combo2_deaths                        int64
combo2_percent                     float64
combo3_drugs                        object
combo3_deaths                        int64
combo3_percent                     float64
combo4_drugs                        object
combo4_deaths                        int64
combo4_percent                     float64
combo5_drugs                        object
combo5_deaths                        int64
combo5_percent                     float64
opioids_stim_deaths                  int64
opioids_stim_percent               float64
opioids_nostim_deaths                int64
opioids_nostim_percent             float64
stim_noopioids_deaths                int64
stim_noopioids_percent             float64
noopioids_nostim_deaths              int64
noopioids_nostim_percent           float64
carfentanil_deaths                   int64
carfentanil_percent                 object
parafluorofentanyl_deaths            int64
parafluorofentanyl_percent          object
other_illegal_opioids_deaths         int64
other_illegal_opioids_percent       object
nitazenes_deaths                     int64
nitazenes_percent                   object
isotonitazene_deaths                 int64
isotonitazene_percent               object
metonitazene_deaths                  int64
metonitazene_percent                object
adulterants_sedatives_deaths         int64
adulterants_sedatives_percent       object
xylazine_deaths                      int64
xylazine_percent                    object
gabapentin_deaths                    int64
gabapentin_percent                  object
illegal_benzodiazepines_deaths       int64
illegal_benzodiazepines_percent     object
bromazolam_deaths                    int64
bromazolam_percent                  object
etizolam_deaths                      int64
etizolam_percent                    object
flualprazolam_deaths                 int64
flualprazolam_percent               object
ketamine_deaths                      int64
ketamine_percent                    object
kratom_deaths                        int64
kratom_percent                      object
synthetic_cannabinoid_deaths         int64
synthetic_cannabinoid_percent       object
cathinones_deaths                    int64
cathinones_percent                  object
jan_deaths                           int64
feb_deaths                           int64
mar_deaths                           int64
apr_deaths                           int64
may_deaths                           int64
jun_deaths                           int64
jul_deaths                           int64
aug_deaths                           int64
sep_deaths                           int64
oct_deaths                           int64
nov_deaths                           int64
dec_deaths                           int64
male_deaths                          int64
male_rate                          float64
male_percent                       float64
female_deaths                        int64
female_rate                        float64
female_percent                     float64
aian_nh_deaths                       int64
aian_nh_rate                       float64
aian_nh_percent                     object
asian_nh_deaths                      int64
asian_nh_rate                      float64
asian_nh_percent                    object
black_nh_deaths                      int64
black_nh_rate                      float64
black_nh_percent                   float64
multi_nh_deaths                      int64
multi_nh_rate                      float64
multi_nh_percent                   float64
nhpi_nh_deaths                       int64
nhpi_nh_rate                       float64
nhpi_nh_percent                     object
white_nh_deaths                      int64
white_nh_rate                      float64
white_nh_percent                   float64
hisp_deaths                          int64
hisp_rate                          float64
hisp_percent                       float64
age_under15_deaths                   int64
age_under15_rate                   float64
age_under15_percent                 object
age_15_24_deaths                     int64
age_15_24_rate                     float64
age_15_24_percent                  float64
age_25_34_deaths                     int64
age_25_34_rate                     float64
age_25_34_percent                  float64
age_35_44_deaths                     int64
age_35_44_rate                     float64
age_35_44_percent                  float64
age_45_54_deaths                     int64
age_45_54_rate                     float64
age_45_54_percent                  float64
age_55_64_deaths                     int64
age_55_64_rate                     float64
age_55_64_percent                  float64
age_65plus_deaths                    int64
age_65plus_rate                    float64
age_65plus_percent                 float64
male_under15_deaths                  int64
male_under15_rate                  float64
male_under15_percent                object
male_15_24_deaths                    int64
male_15_24_rate                    float64
male_15_24_percent                 float64
male_25_34_deaths                    int64
male_25_34_rate                    float64
male_25_34_percent                 float64
male_35_44_deaths                    int64
male_35_44_rate                    float64
male_35_44_percent                 float64
male_45_54_deaths                    int64
male_45_54_rate                    float64
male_45_54_percent                 float64
male_55_64_deaths                    int64
male_55_64_rate                    float64
male_55_64_percent                 float64
male_65plus_deaths                   int64
male_65plus_rate                   float64
male_65plus_percent                float64
female_under15_deaths                int64
female_under15_rate                float64
female_under15_percent             float64
female_15_24_deaths                  int64
female_15_24_rate                  float64
female_15_24_percent               float64
female_25_34_deaths                  int64
female_25_34_rate                  float64
female_25_34_percent               float64
female_35_44_deaths                  int64
female_35_44_rate                  float64
female_35_44_percent               float64
female_45_54_deaths                  int64
female_45_54_rate                  float64
female_45_54_percent               float64
female_55_64_deaths                  int64
female_55_64_rate                  float64
female_55_64_percent               float64
female_65plus_deaths                 int64
female_65plus_rate                 float64
female_65plus_percent              float64
intervopp_deaths                     int64
intervopp_percent                  float64
curr_SUDtrt_deaths                   int64
curr_SUDtrt_percent                float64
drugusewitnessed_deaths              int64
drugusewitnessed_percent           float64
mhdiag_deaths                        int64
mhdiag_percent                     float64
bystander_deaths                     int64
bystander_percent                  float64
priorod_deaths                       int64
priorod_percent                    float64
recentrelease_deaths                 int64
recentrelease_percent              float64
byst_noresp_deaths                   int64
byst_noresp_percent                float64
byst_space_deaths                    int64
byst_space_percent                 float64
byst_unaware_deaths                  int64
byst_unaware_percent               float64
byst_notrecog_deaths                 int64
byst_notrecog_percent              float64
byst_notrecog_od_deaths              int64
byst_notrecog_od_percent           float64
byst_sub_alc_deaths                  int64
byst_sub_alc_percent               float64
byst_publicspace_deaths              int64
byst_publicspace_percent           float64
hx_anydrug_deaths                    int64
hx_anydrug_percent                 float64
hx_opioid_deaths                     int64
hx_opioid_percent                  float64
hx_stim_deaths                       int64
hx_stim_percent                    float64
recentopioid_deaths                  int64
recentopioid_percent               float64
priorod_mon_deaths                   int64
priorod_mon_percent                float64
ever_MHSUDtrt_deaths                 int64
ever_MHSUDtrt_percent              float64
curr_MHSUDtrt_deaths                 int64
curr_MHSUDtrt_percent              float64
hx_selfharm_deaths                   int64
hx_selfharm_percent                float64
od_house_apt_deaths                  int64
od_house_apt_percent               float64
od_home_deaths                       int64
od_home_percent                    float64
od_hotel_deaths                      int64
od_hotel_percent                   float64
homeless_deaths                      int64
homeless_percent                   float64
curr_paintrt_deaths                  int64
curr_paintrt_percent               float64
nopulse_deaths                       int64
nopulse_percent                    float64
naloxone_deaths                      int64
naloxone_percent                   float64
ed_deaths                            int64
ed_percent                         float64
hospital_deaths                      int64
hospital_percent                   float64
ingestion_deaths                     int64
ingestion_percent                  float64
injection_deaths                     int64
injection_percent                  float64
smoking_deaths                       int64
smoking_percent                    float64
snorting_deaths                      int64
snorting_percent                   float64
otherroute_deaths                    int64
otherroute_percent                  object
noroute_deaths                       int64
noroute_percent                    float64
rx_drugs_deaths                      int64
rx_drugs_percent                   float64
illegal_drugs_deaths                 int64
illegal_drugs_percent              float64
counterfeit_pills_deaths             int64
counterfeit_pills_percent          float64
ever_SUDtrt_deaths                   int64
ever_SUDtrt_percent                float64
rx_OUD_deaths                        int64
rx_OUD_percent                     float64
dtype: object

In [48]:
categorical_df.dtypes

Jurisdiction                       object
combo1_drugs                       object
combo2_drugs                       object
combo3_drugs                       object
combo4_drugs                       object
combo5_drugs                       object
carfentanil_percent                object
parafluorofentanyl_percent         object
other_illegal_opioids_percent      object
nitazenes_percent                  object
isotonitazene_percent              object
metonitazene_percent               object
adulterants_sedatives_percent      object
xylazine_percent                   object
gabapentin_percent                 object
illegal_benzodiazepines_percent    object
bromazolam_percent                 object
etizolam_percent                   object
flualprazolam_percent              object
ketamine_percent                   object
kratom_percent                     object
synthetic_cannabinoid_percent      object
cathinones_percent                 object
aian_nh_percent                    object
asian_nh_percent                   object
nhpi_nh_percent                    object
age_under15_percent                object
male_under15_percent               object
otherroute_percent                 object
dtype: object

In [46]:
df_clean['ketamine_percent'].unique()

array(['0', '0.7', '0.2', '0.5', '0.3', '0.8', '1.3', '0.9', '0.4', '1.2',
       '0.6', '1.6', '1', '0.1', '1.1', '1.9', '2.3', '1.5', '1.4', '2'],
      dtype=object)

In [55]:
bb = df_clean.copy()
bb['ketamine_percent'] = df_clean['ketamine_percent'].astype(float)
bb.dtypes

Jurisdiction                        object
year                                 int64
alldrug_deaths                       int64
alldrug_rate                       float64
opioids_deaths                       int64
opioids_rate                       float64
imfs_deaths                          int64
imfs_rate                          float64
heroin_deaths                        int64
heroin_rate                        float64
rxopioids_deaths                     int64
rxopioids_rate                     float64
stimulant_deaths                     int64
stimulant_rate                     float64
cocaine_deaths                       int64
cocaine_rate                       float64
meth_deaths                          int64
meth_rate                          float64
nonopioid_sedatives_deaths           int64
nonopioid_sedatives_rate           float64
benzodiazepines_deaths               int64
benzodiazepines_rate               float64
opioids_percent                    float64
imfs_percent                       float64
heroin_percent                     float64
rxopioids_percent                  float64
stimulant_percent                  float64
cocaine_percent                    float64
meth_percent                       float64
nonopioid_sedatives_percent        float64
benzodiazepines_percent            float64
combo1_drugs                        object
combo1_deaths                        int64
combo1_percent                     float64
combo2_drugs                        object
combo2_deaths                        int64
combo2_percent                     float64
combo3_drugs                        object
combo3_deaths                        int64
combo3_percent                     float64
combo4_drugs                        object
combo4_deaths                        int64
combo4_percent                     float64
combo5_drugs                        object
combo5_deaths                        int64
combo5_percent                     float64
opioids_stim_deaths                  int64
opioids_stim_percent               float64
opioids_nostim_deaths                int64
opioids_nostim_percent             float64
stim_noopioids_deaths                int64
stim_noopioids_percent             float64
noopioids_nostim_deaths              int64
noopioids_nostim_percent           float64
carfentanil_deaths                   int64
carfentanil_percent                 object
parafluorofentanyl_deaths            int64
parafluorofentanyl_percent          object
other_illegal_opioids_deaths         int64
other_illegal_opioids_percent       object
nitazenes_deaths                     int64
nitazenes_percent                   object
isotonitazene_deaths                 int64
isotonitazene_percent               object
metonitazene_deaths                  int64
metonitazene_percent                object
adulterants_sedatives_deaths         int64
adulterants_sedatives_percent       object
xylazine_deaths                      int64
xylazine_percent                    object
gabapentin_deaths                    int64
gabapentin_percent                  object
illegal_benzodiazepines_deaths       int64
illegal_benzodiazepines_percent     object
bromazolam_deaths                    int64
bromazolam_percent                  object
etizolam_deaths                      int64
etizolam_percent                    object
flualprazolam_deaths                 int64
flualprazolam_percent               object
ketamine_deaths                      int64
ketamine_percent                   float64
kratom_deaths                        int64
kratom_percent                      object
synthetic_cannabinoid_deaths         int64
synthetic_cannabinoid_percent       object
cathinones_deaths                    int64
cathinones_percent                  object
jan_deaths                           int64
feb_deaths                           int64
mar_deaths                           int64
apr_deaths                           int64
may_deaths                           int64
jun_deaths                           int64
jul_deaths                           int64
aug_deaths                           int64
sep_deaths                           int64
oct_deaths                           int64
nov_deaths                           int64
dec_deaths                           int64
male_deaths                          int64
male_rate                          float64
male_percent                       float64
female_deaths                        int64
female_rate                        float64
female_percent                     float64
aian_nh_deaths                       int64
aian_nh_rate                       float64
aian_nh_percent                     object
asian_nh_deaths                      int64
asian_nh_rate                      float64
asian_nh_percent                    object
black_nh_deaths                      int64
black_nh_rate                      float64
black_nh_percent                   float64
multi_nh_deaths                      int64
multi_nh_rate                      float64
multi_nh_percent                   float64
nhpi_nh_deaths                       int64
nhpi_nh_rate                       float64
nhpi_nh_percent                     object
white_nh_deaths                      int64
white_nh_rate                      float64
white_nh_percent                   float64
hisp_deaths                          int64
hisp_rate                          float64
hisp_percent                       float64
age_under15_deaths                   int64
age_under15_rate                   float64
age_under15_percent                 object
age_15_24_deaths                     int64
age_15_24_rate                     float64
age_15_24_percent                  float64
age_25_34_deaths                     int64
age_25_34_rate                     float64
age_25_34_percent                  float64
age_35_44_deaths                     int64
age_35_44_rate                     float64
age_35_44_percent                  float64
age_45_54_deaths                     int64
age_45_54_rate                     float64
age_45_54_percent                  float64
age_55_64_deaths                     int64
age_55_64_rate                     float64
age_55_64_percent                  float64
age_65plus_deaths                    int64
age_65plus_rate                    float64
age_65plus_percent                 float64
male_under15_deaths                  int64
male_under15_rate                  float64
male_under15_percent                object
male_15_24_deaths                    int64
male_15_24_rate                    float64
male_15_24_percent                 float64
male_25_34_deaths                    int64
male_25_34_rate                    float64
male_25_34_percent                 float64
male_35_44_deaths                    int64
male_35_44_rate                    float64
male_35_44_percent                 float64
male_45_54_deaths                    int64
male_45_54_rate                    float64
male_45_54_percent                 float64
male_55_64_deaths                    int64
male_55_64_rate                    float64
male_55_64_percent                 float64
male_65plus_deaths                   int64
male_65plus_rate                   float64
male_65plus_percent                float64
female_under15_deaths                int64
female_under15_rate                float64
female_under15_percent             float64
female_15_24_deaths                  int64
female_15_24_rate                  float64
female_15_24_percent               float64
female_25_34_deaths                  int64
female_25_34_rate                  float64
female_25_34_percent               float64
female_35_44_deaths                  int64
female_35_44_rate                  float64
female_35_44_percent               float64
female_45_54_deaths                  int64
female_45_54_rate                  float64
female_45_54_percent               float64
female_55_64_deaths                  int64
female_55_64_rate                  float64
female_55_64_percent               float64
female_65plus_deaths                 int64
female_65plus_rate                 float64
female_65plus_percent              float64
intervopp_deaths                     int64
intervopp_percent                  float64
curr_SUDtrt_deaths                   int64
curr_SUDtrt_percent                float64
drugusewitnessed_deaths              int64
drugusewitnessed_percent           float64
mhdiag_deaths                        int64
mhdiag_percent                     float64
bystander_deaths                     int64
bystander_percent                  float64
priorod_deaths                       int64
priorod_percent                    float64
recentrelease_deaths                 int64
recentrelease_percent              float64
byst_noresp_deaths                   int64
byst_noresp_percent                float64
byst_space_deaths                    int64
byst_space_percent                 float64
byst_unaware_deaths                  int64
byst_unaware_percent               float64
byst_notrecog_deaths                 int64
byst_notrecog_percent              float64
byst_notrecog_od_deaths              int64
byst_notrecog_od_percent           float64
byst_sub_alc_deaths                  int64
byst_sub_alc_percent               float64
byst_publicspace_deaths              int64
byst_publicspace_percent           float64
hx_anydrug_deaths                    int64
hx_anydrug_percent                 float64
hx_opioid_deaths                     int64
hx_opioid_percent                  float64
hx_stim_deaths                       int64
hx_stim_percent                    float64
recentopioid_deaths                  int64
recentopioid_percent               float64
priorod_mon_deaths                   int64
priorod_mon_percent                float64
ever_MHSUDtrt_deaths                 int64
ever_MHSUDtrt_percent              float64
curr_MHSUDtrt_deaths                 int64
curr_MHSUDtrt_percent              float64
hx_selfharm_deaths                   int64
hx_selfharm_percent                float64
od_house_apt_deaths                  int64
od_house_apt_percent               float64
od_home_deaths                       int64
od_home_percent                    float64
od_hotel_deaths                      int64
od_hotel_percent                   float64
homeless_deaths                      int64
homeless_percent                   float64
curr_paintrt_deaths                  int64
curr_paintrt_percent               float64
nopulse_deaths                       int64
nopulse_percent                    float64
naloxone_deaths                      int64
naloxone_percent                   float64
ed_deaths                            int64
ed_percent                         float64
hospital_deaths                      int64
hospital_percent                   float64
ingestion_deaths                     int64
ingestion_percent                  float64
injection_deaths                     int64
injection_percent                  float64
smoking_deaths                       int64
smoking_percent                    float64
snorting_deaths                      int64
snorting_percent                   float64
otherroute_deaths                    int64
otherroute_percent                  object
noroute_deaths                       int64
noroute_percent                    float64
rx_drugs_deaths                      int64
rx_drugs_percent                   float64
illegal_drugs_deaths                 int64
illegal_drugs_percent              float64
counterfeit_pills_deaths             int64
counterfeit_pills_percent          float64
ever_SUDtrt_deaths                   int64
ever_SUDtrt_percent                float64
rx_OUD_deaths                        int64
rx_OUD_percent                     float64
dtype: object